cards/urls.py
from django.urls import path
from .views import CardCreateView, CardUpdateView, CardDetailView, delete_card, CardListView

urlpatterns = [
    # ==============================*** Card URLS ***==============================
    path("create/", CardCreateView.as_view(), name="create_card"),
    # path("update/<slug>/", CardUpdateView.as_view(), name="update_card"),
    path("<slug>/detail/", CardDetailView.as_view(), name="card_detail"),
    # path("delete/", delete_card, name="delete_card"),
    # Card List View for admin usage
    path("list/", CardListView.as_view(), name="admin_card_list"),
]

invoice/urls.py
from django.urls import path
from .views import InvoiceCreateView, InvoiceUpdateView, InvoiceDetailView, delete_invoice, GeneratePdf, CompanyInvoiceListView

urlpatterns = [
    # ==============================*** Invoice URLS ***==============================
    path("create/", InvoiceCreateView.as_view(), name="create_invoice"),
    path("update/<slug>/", InvoiceUpdateView.as_view(), name="update_invoice"),
    path("<slug>/detail/", InvoiceDetailView.as_view(), name="invoice_detail"),
    path("delete/", delete_invoice, name="delete_invoice"),
    # PDF URLs
    path("<slug>/pdf/", GeneratePdf.as_view(), name="invoice_pdf_download"),
    # Company Invoice List
    path("list/", CompanyInvoiceListView.as_view(), name="company_invoice_list"),
]

invoice/forms.py
from django import forms
from utils.mixins import CustomModelForm
from .models import Invoice
from deals.models import Coupon, Vat
from company.models import Company
from service.models import Service
from django_select2.forms import ModelSelect2MultipleWidget, ModelSelect2Widget



class InvoiceManageForm(CustomModelForm):
    
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        self.object = kwargs.pop('object', None)
        super(InvoiceManageForm, self).__init__(*args, **kwargs)
        
        if self.object and len(self.object.service.all()) > 0:
            self.initial['company'] = self.object.service.first().company
            
    try:
    
        company = forms.ModelChoiceField(
            queryset=Company.objects.filter(is_active=True),
            label=u"Company",
            empty_label="Select Company...",
            widget=ModelSelect2Widget(
                model=Company,
                search_fields=['name__icontains'],
                max_results=500,
                attrs={'data-minimum-input-length': '0'}
            )
        )

        service = forms.ModelMultipleChoiceField(
            queryset=Service.objects.all(),
            label=u"Service",
            widget=ModelSelect2MultipleWidget(
                model=Service,
                search_fields=['name__icontains', 'company__name__icontains'],
                dependent_fields={'company': 'company'},
                max_results=500,
                attrs={'data-minimum-input-length': '0'}
            )
        )
        
        coupon = forms.ModelChoiceField(
            queryset=Coupon.objects.filter(is_active=True),
            required=False,
            label=u"Coupon",
            empty_label="Select Coupon...",
            widget=ModelSelect2Widget(
                model=Coupon,
                search_fields=['code__icontains', 'discount_amount__icontains'],
                max_results=500,
                attrs={'data-minimum-input-length': '0'}
            )
        )
        
        vat = forms.ModelChoiceField(
            queryset=Vat.objects.filter(is_active=True),
            required=False,
            initial=Vat.objects.filter(is_active=True).last(),
            label=u"Vat",
            empty_label="Select Vat..."
        )
    except Exception as e:
        
        print("*********** Exception: Invoice->forms.py: ", e, "***********")
    
    class Meta:
        model = Invoice
        fields = ("company", "service", "coupon", "vat", "additional_charge", "card_number", "status")
        exclude = ('slug', 'total_cost', 'created_at', 'created_at')
        

    def clean_company(self):
        company = self.cleaned_data.get('company')

        if not company:
            raise forms.ValidationError("Company is required!!")

        return company

    def clean_service(self):
        service = self.cleaned_data.get('service')

        if not service == None:
            company_ids = service.all().values_list('company', flat=True)
            if len(set(company_ids)) > 1:
                raise forms.ValidationError("Services should belong to same company!")

        return service

    def clean_coupon(self):
        coupon = self.cleaned_data.get('coupon')

        if not coupon == None:
            qs = Coupon.objects.filter(code__iexact=coupon.code)
            if not qs:
                raise forms.ValidationError("Invalid Coupon!")
            if qs and not qs.last().is_active:
                raise forms.ValidationError("Coupon Expired!")

        return coupon

    def clean_vat(self):
        vat = self.cleaned_data.get('vat')

        if not vat == None:
            qs = Vat.objects.filter(slug__iexact=vat.slug)
            if not qs:
                raise forms.ValidationError("Vat not exists!")
            if qs and not qs.last().is_active:
                raise forms.ValidationError("Vat is not active!")

        return vat

invoice/views.py
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from company.models import Company
from utils.decorators import has_dashboard_permission_required
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.contrib import messages
from utils.helpers import (
    get_simple_context_data, get_simple_object, delete_simple_object
)
from django.conf import settings
import json
import os
from django.http import HttpResponseRedirect
# PDF imports
from django.views.generic import View
from utils.snippets import generate_pdf_with_pdfkit
from django.utils import timezone
# App Imports
from .forms import InvoiceManageForm
from .models import Invoice
from service.models import Service



dashboard_decorators = [login_required, has_dashboard_permission_required]



""" 
-------------------------------------------------------------------
                        *** Invoice ***
-------------------------------------------------------------------
"""


def get_invoice_common_contexts(request):
    extra_kwargs = {}
    STATIC_DATA_FILE = os.path.join(settings.BASE_DIR, 'utils/staticData.json')
    # Opening JSON file
    data_file = open(STATIC_DATA_FILE,)
    data = json.load(data_file)
    comapny_information = data.get("CompanyInformation", {})
    extra_kwargs.update({"company_information": comapny_information})
    # service lists
    services = Service.objects.all()
    extra_kwargs.update({"services": services})
    
    common_contexts = get_simple_context_data(
        request=request, app_namespace='invoice', model_namespace="invoice", model=Invoice, list_template="invoice/invoice-list.html", fields_to_hide_in_table=["id", "slug", "updated_at", "card_number"], **extra_kwargs
    )
    # update fields count in context
    common_contexts.update({"fields_count": common_contexts["fields_count"] + 2})
    return common_contexts


@method_decorator(dashboard_decorators, name='dispatch')
class InvoiceCreateView(CreateView):
    template_name = "admin_panel/snippets/manage.html"
    form_class = InvoiceManageForm

    def form_valid(self, form, **kwargs):
        messages.success(
            self.request, 'Invoice created successfully!'
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("invoice:create_invoice")

    def get_context_data(self, **kwargs):
        context = super(
            InvoiceCreateView, self
        ).get_context_data(**kwargs)
        context['page_title'] = 'Create Invoice'
        context['page_short_title'] = 'Create Invoice'
        for key, value in get_invoice_common_contexts(request=self.request).items():
            context[key] = value
        return context


@method_decorator(login_required, name='dispatch')
class InvoiceDetailView(DetailView):
    template_name = "invoice/invoice-detail.html"

    def get_object(self):
        return get_simple_object(key='slug', model=Invoice, self=self)
    
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        is_superuser = request.user.is_superuser
        is_company = True if self.object.service.filter(company__user=request.user).exists() else False
        if not is_superuser and not is_company:
            messages.error(
                self.request, 'Access Denied!'
            )
            return HttpResponseRedirect(reverse('home'))
        return super(InvoiceDetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(
            InvoiceDetailView, self
        ).get_context_data(**kwargs)
        context['page_title'] = f'Invoice - {self.get_object().__str__()} Detail'
        context['page_short_title'] = f'Invoice - {self.get_object().__str__()} Detail'
        for key, value in get_invoice_common_contexts(request=self.request).items():
            context[key] = value
        return context


@method_decorator(dashboard_decorators, name='dispatch')
class InvoiceUpdateView(UpdateView):
    template_name = 'admin_panel/snippets/manage.html'
    form_class = InvoiceManageForm

    def get_object(self):
        return get_simple_object(key="slug", model=Invoice, self=self)
    
    def get_form_kwargs(self):
        kwargs = super(InvoiceUpdateView, self).get_form_kwargs()
        if self.form_class:
            kwargs.update({'request': self.request})
            kwargs.update({'object': self.get_object()})
        return kwargs

    def get_success_url(self):
        return reverse("invoice:create_invoice")

    def form_valid(self, form):
        messages.success(
            self.request, 'Invoice updated successfully!'
        )
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(
            InvoiceUpdateView, self
        ).get_context_data(**kwargs)
        context['page_title'] = f'Update Invoice "{self.get_object().__str__()}"'
        context['page_short_title'] = f'Update Invoice "{self.get_object().__str__()}"'
        for key, value in get_invoice_common_contexts(request=self.request).items():
            context[key] = value
        return context


@csrf_exempt
@has_dashboard_permission_required
@login_required
def delete_invoice(request):
    return delete_simple_object(request=request, key='slug', model=Invoice, redirect_url="invoice:create_invoice")


""" 
-------------------------------------------------------------------
                        *** PDF ***
-------------------------------------------------------------------
"""

@method_decorator(login_required, name='dispatch')
class GeneratePdf(View):
    def get(self, request, *args, **kwargs):
        # Object
        self.object = get_simple_object(key="slug", model=Invoice, self=self)
        # Company Information
        STATIC_DATA_FILE = os.path.join(settings.BASE_DIR, 'utils/staticData.json')
        # Open and read JSON file
        data_file = open(STATIC_DATA_FILE,)
        data = json.load(data_file)
        comapny_information = data.get("CompanyInformation", {})
        # prepare context data
        context = {
            "object": self.object,
            "company_information": comapny_information,
            "datetime": timezone.now(),
        }
        
        # define required stylesheets
        css =  [
            os.path.join(settings.BASE_DIR, 'staticfiles/admin_panel/assets/css/bootstrap.css'), os.path.join(
                settings.BASE_DIR, 'staticfiles/admin_panel/assets/css/custom.css')
        ]
        
        def create_file_name():
            file_name = '%s Invoice.pdf' % (self.object.get_company())
            return file_name.strip()

        # generate and download PDF
        response = generate_pdf_with_pdfkit(
            template_src="invoice/snippets/invoice-pdf-preview.html",
            context=context,
            css=css,
            filename=create_file_name()
        )
        return response
    
    def dispatch(self, request, *args, **kwargs):
        self.object = get_simple_object(key="slug", model=Invoice, self=self)
        is_superuser = request.user.is_superuser
        is_company = True if self.object.service.filter(
            company__user=request.user).exists() else False
        if not is_superuser and not is_company:
            messages.error(
                self.request, 'Access Denied!'
            )
            return HttpResponseRedirect(reverse('home'))
        return super(GeneratePdf, self).dispatch(request, *args, **kwargs)
    
    
""" 
-------------------------------------------------------------------
                    *** Company Invoice List ***
-------------------------------------------------------------------
"""


@method_decorator(login_required, name='dispatch')
class CompanyInvoiceListView(ListView):
    template_name = "invoice/company-invoice-list.html"
    
    def get_queryset(self):
        qs = None
        company_qs = Company.objects.filter(user=self.request.user)
        if company_qs:
            company = company_qs.first()
            qs = Invoice.objects.filter(service__company=company)
            
        return qs
    
    def dispatch(self, request, *args, **kwargs):
        is_superuser = request.user.is_superuser
        is_company = True if self.request.user.is_company else False
        if not is_superuser and not is_company:
            messages.error(
                self.request, 'Access Denied!'
            )
            return HttpResponseRedirect(reverse('home'))
        return super(CompanyInvoiceListView, self).dispatch(request, *args, **kwargs)
    
    
    def get_context_data(self, **kwargs):
        context = super(
            CompanyInvoiceListView, self
        ).get_context_data(**kwargs)
        context['page_title'] = 'Invoice List'
        context['page_short_title'] = 'Invoice List'
        context['display_name'] = 'Invoice List'
        context['can_view'] = True
        return context

invoice/templates/invoice/company-invoice-list.html
{% extends "admin_panel/base.html" %}
{% load static %}
{% load custom_tags %}

{% block content %}

{% if can_view == True %}

{% autoescape off %}

<!-- Page content -->
<div class="row">
    <div class="col">
        <div class="card">
            <!-- Card header -->
            <div class="card-header border-0 text-center">
                <h3 class="mb-0">
                    {% if not display_name == None %}
                    {{ display_name }}
                    {% else %}
                    {{ namespace|to_title }}
                    {% endif %}
                </h3>
            </div>
            <!-- Light table -->
            <div class="table-responsive">
                <table id="list-datatable" class="display table align-items-center table-flush table-hover"
                    style="width:100%">
                    <thead class="">
                        <tr class="text-center">
                            <th>Action</th>
                            <th>#</th>
                            <th>uuid</th>
                            <th>service</th>
                            <th>coupon</th>
                            <th>vat</th>
                            <th>additional charge</th>
                            <th>total cost</th>
                            <th>status</th>
                            <th>created at</th>
                        </tr>
                    </thead>

                    <tbody class="list">

                        <!-- table body -->
                        {% for object in object_list %}
                        <tr class="text-center">

                            <th width="10">
                                <!-- invoice view button -->
                                <a href="{% url 'invoice:invoice_detail' slug=object.slug %}"
                                    class="btn btn-primary btn-sm m-1 text-deco-none">
                                    <span class="">
                                        <i class="fas fa-eye" aria-hidden="true"></i>
                                    </span>
                                </a>
                            </th>

                            <th>{{ forloop.counter }}</th>

                            <td>{{ object.uuid }}</td>
                            <td>{{ object }}</td>
                            <td>
                                {% if object.coupon %}
                                {{ object.coupon }}
                                {% else %}
                                ---
                                {% endif %}
                            </td>
                            <td>
                                {% if object.vat %}
                                {{ object.vat.vat_percentage }}%
                                {% else %}
                                ---
                                {% endif %}
                            </td>
                            <td>
                                {% if object.additional_charge %}
                                {{ object.additional_charge }} {{ object.get_currency }}
                                {% else %}
                                ---
                                {% endif %}
                            </td>
                            <td>
                                {{ object.total_cost }} {{ object.get_currency }}
                            </td>
                            <td>
                                {% if object.status == 0 %}
                                <i class="fas fa-times-circle text-danger fw-bold"></i>
                                {% elif object.status == 1 %}
                                <i class="fas fa-check-circle text-success fw-bold"></i>
                                {% else %}
                                <i class="fas fa-sync-alt text-warning fw-bold"></i>
                                {% endif %}

                                {{ object.get_status_str }}
                            </td>
                            <td>{{ object.created_at }}</td>

                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="10" class="text-center">
                                <div class="alert alert-info">
                                    No item found!
                                </div>
                            </td>
                        </tr>
                        {% endfor %}

                    </tbody>

                    <tfoot class="">
                        <tr class="text-center">
                            <th>Action</th>
                            <th>#</th>
                            <th>uuid</th>
                            <th>service</th>
                            <th>coupon</th>
                            <th>vat</th>
                            <th>additional charge</th>
                            <th>total cost</th>
                            <th>status</th>
                            <th>created at</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

{% endautoescape %}

{% endif %}

{% endblock %}

invoice/templates/invoice/invoice-detail.html
{% extends 'admin_panel/base.html' %}

{% load static %}

{% load custom_tags %}

{% block head_title %}
{% block page_short_title %}
{% block breadcrumb %}
{{ page_short_title }}
{% endblock %}
{% endblock %}
{% endblock %}
{% block page_title %}
{{ page_title }}
{% endblock %}


{% block content %}

{% if can_view == True %}

{% autoescape off %}

<div class="card">
    <div class="card-header">
        <h4 class="card-title text-center">
            <span class="">{{ page_title }}</span>
        </h4>

        {% if request.user.is_superuser %}
        {% if not list_url == None or not create_url == None or not update_url == None or not delete_url == None %}
        <div class="text-center">

            {% if not create_url == None and can_add_change == True %}
            <a href="{% url create_url %}" class="btn btn-primary">
                <i class="fas fa-plus"></i>
            </a>
            {% endif %}

            {% if not update_url == None and can_add_change == True %}
            {% if not object.slug == None %}
            <a href="{% url update_url slug=object.slug %}" class="btn btn-primary">
                <span class="">
                    <i class="fas fa-edit"></i>
                </span>
            </a>
            {% else %}
            <a href="{% url update_url id=object.id %}" class="btn btn-primary">
                <span class="">
                    <i class="fas fa-edit"></i>
                </span>
            </a>
            {% endif %}

            {% endif %}
            {% if not list_url == None and can_view == True %}
            <a href="{% url list_url %}" class="btn btn-primary" alt="Show List">
                <i class="fas fa-list"></i>
            </a>
            {% endif %}

            {% if can_delete == True %}
            {% if not delete_url == None %}
            {% if not object.slug == None %}
            <button type="button" class="btn btn-danger btn-xs text-deco-none bg-c-danger m-1 js_delete_{{namespace}}"
                value="{{object.slug}}" data-toggle="modal" data-target="#modal-delete-{{namespace}}">
                <i class="fas fa-trash-alt"></i>
            </button>
            {% else %}
            <button type="button" class="btn btn-danger btn-xs text-deco-none bg-c-danger m-1 js_delete_{{namespace}}"
                value="{{object.id}}" data-toggle="modal" data-target="#modal-delete-{{namespace}}">
                <i class="fas fa-trash-alt"></i>
            </button>
            {% endif %}
            {% endif %}
            {% endif %}
        </div>
        {% endif %}

        {% endif %}
        
    </div>

    <!-- invoice preview -->

    <div class="card-body printableArea p-lg-5">

        {% include "invoice/snippets/invoice-preview.html" %}
        
    </div>


</div>

{% endautoescape %}

{% endif %}


{% if not delete_url == None and can_delete == True %}
{% include 'admin_panel/snippets/delete-modal.html' %}
{% endif %}

{% endblock %}

{% block additional_js %}
<!-- EZ View JS -->
<script src="{% static 'assets/vendors/ez-view/EZView.js' %}"></script>
<script src="{% static 'assets/vendors/ez-view/draggable.js' %}"></script>
<script src="{% static 'assets/vendors/ez-view/ez-conf.js' %}"></script>

{% endblock %}