cards/urls.py
from django.urls import path
from .views import CardCreateView, CardUpdateView, CardDetailView, delete_card, CardListView

urlpatterns = [
    # ==============================*** Card URLS ***==============================
    path("create/", CardCreateView.as_view(), name="create_card"),
    # path("update/<slug>/", CardUpdateView.as_view(), name="update_card"),
    path("<slug>/detail/", CardDetailView.as_view(), name="card_detail"),
    # path("delete/", delete_card, name="delete_card"),
    # Card List View for admin usage
    path("list/", CardListView.as_view(), name="admin_card_list"),
]

invoice/urls.py
from django.urls import path
from .views import InvoiceCreateView, InvoiceUpdateView, InvoiceDetailView, delete_invoice, GeneratePdf, CompanyInvoiceListView

urlpatterns = [
    # ==============================*** Invoice URLS ***==============================
    path("create/", InvoiceCreateView.as_view(), name="create_invoice"),
    path("update/<slug>/", InvoiceUpdateView.as_view(), name="update_invoice"),
    path("<slug>/detail/", InvoiceDetailView.as_view(), name="invoice_detail"),
    path("delete/", delete_invoice, name="delete_invoice"),
    # PDF URLs
    path("<slug>/pdf/", GeneratePdf.as_view(), name="invoice_pdf_download"),
    # Company Invoice List
    path("list/", CompanyInvoiceListView.as_view(), name="company_invoice_list"),
]

invoice/forms.py
from django import forms
from utils.mixins import CustomModelForm
from .models import Invoice
from deals.models import Coupon, Vat
from company.models import Company
from service.models import Service
from django_select2.forms import ModelSelect2MultipleWidget, ModelSelect2Widget



class InvoiceManageForm(CustomModelForm):
    
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        self.object = kwargs.pop('object', None)
        super(InvoiceManageForm, self).__init__(*args, **kwargs)
        
        if self.object and len(self.object.service.all()) > 0:
            self.initial['company'] = self.object.service.first().company
            
    try:
    
        company = forms.ModelChoiceField(
            queryset=Company.objects.filter(is_active=True),
            label=u"Company",
            empty_label="Select Company...",
            widget=ModelSelect2Widget(
                model=Company,
                search_fields=['name__icontains'],
                max_results=500,
                attrs={'data-minimum-input-length': '0'}
            )
        )

        service = forms.ModelMultipleChoiceField(
            queryset=Service.objects.all(),
            label=u"Service",
            widget=ModelSelect2MultipleWidget(
                model=Service,
                search_fields=['name__icontains', 'company__name__icontains'],
                dependent_fields={'company': 'company'},
                max_results=500,
                attrs={'data-minimum-input-length': '0'}
            )
        )
        
        coupon = forms.ModelChoiceField(
            queryset=Coupon.objects.filter(is_active=True),
            required=False,
            label=u"Coupon",
            empty_label="Select Coupon...",
            widget=ModelSelect2Widget(
                model=Coupon,
                search_fields=['code__icontains', 'discount_amount__icontains'],
                max_results=500,
                attrs={'data-minimum-input-length': '0'}
            )
        )
        
        vat = forms.ModelChoiceField(
            queryset=Vat.objects.filter(is_active=True),
            required=False,
            initial=Vat.objects.filter(is_active=True).last(),
            label=u"Vat",
            empty_label="Select Vat..."
        )
    except Exception as e:
        
        print("*********** Exception: Invoice->forms.py: ", e, "***********")
    
    class Meta:
        model = Invoice
        fields = ("company", "service", "coupon", "vat", "additional_charge", "card_number", "status")
        exclude = ('slug', 'total_cost', 'created_at', 'created_at')
        

    def clean_company(self):
        company = self.cleaned_data.get('company')

        if not company:
            raise forms.ValidationError("Company is required!!")

        return company

    def clean_service(self):
        service = self.cleaned_data.get('service')

        if not service == None:
            company_ids = service.all().values_list('company', flat=True)
            if len(set(company_ids)) > 1:
                raise forms.ValidationError("Services should belong to same company!")

        return service

    def clean_coupon(self):
        coupon = self.cleaned_data.get('coupon')

        if not coupon == None:
            qs = Coupon.objects.filter(code__iexact=coupon.code)
            if not qs:
                raise forms.ValidationError("Invalid Coupon!")
            if qs and not qs.last().is_active:
                raise forms.ValidationError("Coupon Expired!")

        return coupon

    def clean_vat(self):
        vat = self.cleaned_data.get('vat')

        if not vat == None:
            qs = Vat.objects.filter(slug__iexact=vat.slug)
            if not qs:
                raise forms.ValidationError("Vat not exists!")
            if qs and not qs.last().is_active:
                raise forms.ValidationError("Vat is not active!")

        return vat

invoice/views.py
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from company.models import Company
from utils.decorators import has_dashboard_permission_required
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.contrib import messages
from utils.helpers import (
    get_simple_context_data, get_simple_object, delete_simple_object
)
from django.conf import settings
import json
import os
from django.http import HttpResponseRedirect
# PDF imports
from django.views.generic import View
from utils.snippets import generate_pdf_with_pdfkit
from django.utils import timezone
# App Imports
from .forms import InvoiceManageForm
from .models import Invoice
from service.models import Service



dashboard_decorators = [login_required, has_dashboard_permission_required]



""" 
-------------------------------------------------------------------
                        *** Invoice ***
-------------------------------------------------------------------
"""


def get_invoice_common_contexts(request):
    extra_kwargs = {}
    STATIC_DATA_FILE = os.path.join(settings.BASE_DIR, 'utils/staticData.json')
    # Opening JSON file
    data_file = open(STATIC_DATA_FILE,)
    data = json.load(data_file)
    comapny_information = data.get("CompanyInformation", {})
    extra_kwargs.update({"company_information": comapny_information})
    # service lists
    services = Service.objects.all()
    extra_kwargs.update({"services": services})
    
    common_contexts = get_simple_context_data(
        request=request, app_namespace='invoice', model_namespace="invoice", model=Invoice, list_template="invoice/invoice-list.html", fields_to_hide_in_table=["id", "slug", "updated_at", "card_number"], **extra_kwargs
    )
    # update fields count in context
    common_contexts.update({"fields_count": common_contexts["fields_count"] + 2})
    return common_contexts


@method_decorator(dashboard_decorators, name='dispatch')
class InvoiceCreateView(CreateView):
    template_name = "admin_panel/snippets/manage.html"
    form_class = InvoiceManageForm

    def form_valid(self, form, **kwargs):
        messages.success(
            self.request, 'Invoice created successfully!'
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("invoice:create_invoice")

    def get_context_data(self, **kwargs):
        context = super(
            InvoiceCreateView, self
        ).get_context_data(**kwargs)
        context['page_title'] = 'Create Invoice'
        context['page_short_title'] = 'Create Invoice'
        for key, value in get_invoice_common_contexts(request=self.request).items():
            context[key] = value
        return context


@method_decorator(login_required, name='dispatch')
class InvoiceDetailView(DetailView):
    template_name = "invoice/invoice-detail.html"

    def get_object(self):
        return get_simple_object(key='slug', model=Invoice, self=self)
    
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        is_superuser = request.user.is_superuser
        is_company = True if self.object.service.filter(company__user=request.user).exists() else False
        if not is_superuser and not is_company:
            messages.error(
                self.request, 'Access Denied!'
            )
            return HttpResponseRedirect(reverse('home'))
        return super(InvoiceDetailView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(
            InvoiceDetailView, self
        ).get_context_data(**kwargs)
        context['page_title'] = f'Invoice - {self.get_object().__str__()} Detail'
        context['page_short_title'] = f'Invoice - {self.get_object().__str__()} Detail'
        for key, value in get_invoice_common_contexts(request=self.request).items():
            context[key] = value
        return context


@method_decorator(dashboard_decorators, name='dispatch')
class InvoiceUpdateView(UpdateView):
    template_name = 'admin_panel/snippets/manage.html'
    form_class = InvoiceManageForm

    def get_object(self):
        return get_simple_object(key="slug", model=Invoice, self=self)
    
    def get_form_kwargs(self):
        kwargs = super(InvoiceUpdateView, self).get_form_kwargs()
        if self.form_class:
            kwargs.update({'request': self.request})
            kwargs.update({'object': self.get_object()})
        return kwargs

    def get_success_url(self):
        return reverse("invoice:create_invoice")

    def form_valid(self, form):
        messages.success(
            self.request, 'Invoice updated successfully!'
        )
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(
            InvoiceUpdateView, self
        ).get_context_data(**kwargs)
        context['page_title'] = f'Update Invoice "{self.get_object().__str__()}"'
        context['page_short_title'] = f'Update Invoice "{self.get_object().__str__()}"'
        for key, value in get_invoice_common_contexts(request=self.request).items():
            context[key] = value
        return context


@csrf_exempt
@has_dashboard_permission_required
@login_required
def delete_invoice(request):
    return delete_simple_object(request=request, key='slug', model=Invoice, redirect_url="invoice:create_invoice")


""" 
-------------------------------------------------------------------
                        *** PDF ***
-------------------------------------------------------------------
"""

@method_decorator(login_required, name='dispatch')
class GeneratePdf(View):
    def get(self, request, *args, **kwargs):
        # Object
        self.object = get_simple_object(key="slug", model=Invoice, self=self)
        # Company Information
        STATIC_DATA_FILE = os.path.join(settings.BASE_DIR, 'utils/staticData.json')
        # Open and read JSON file
        data_file = open(STATIC_DATA_FILE,)
        data = json.load(data_file)
        comapny_information = data.get("CompanyInformation", {})
        # prepare context data
        context = {
            "object": self.object,
            "company_information": comapny_information,
            "datetime": timezone.now(),
        }
        
        # define required stylesheets
        css =  [
            os.path.join(settings.BASE_DIR, 'staticfiles/admin_panel/assets/css/bootstrap.css'), os.path.join(
                settings.BASE_DIR, 'staticfiles/admin_panel/assets/css/custom.css')
        ]
        
        def create_file_name():
            file_name = '%s Invoice.pdf' % (self.object.get_company())
            return file_name.strip()

        # generate and download PDF
        response = generate_pdf_with_pdfkit(
            template_src="invoice/snippets/invoice-pdf-preview.html",
            context=context,
            css=css,
            filename=create_file_name()
        )
        return response
    
    def dispatch(self, request, *args, **kwargs):
        self.object = get_simple_object(key="slug", model=Invoice, self=self)
        is_superuser = request.user.is_superuser
        is_company = True if self.object.service.filter(
            company__user=request.user).exists() else False
        if not is_superuser and not is_company:
            messages.error(
                self.request, 'Access Denied!'
            )
            return HttpResponseRedirect(reverse('home'))
        return super(GeneratePdf, self).dispatch(request, *args, **kwargs)
    
    
""" 
-------------------------------------------------------------------
                    *** Company Invoice List ***
-------------------------------------------------------------------
"""


@method_decorator(login_required, name='dispatch')
class CompanyInvoiceListView(ListView):
    template_name = "invoice/company-invoice-list.html"
    
    def get_queryset(self):
        qs = None
        company_qs = Company.objects.filter(user=self.request.user)
        if company_qs:
            company = company_qs.first()
            qs = Invoice.objects.filter(service__company=company)
            
        return qs
    
    def dispatch(self, request, *args, **kwargs):
        is_superuser = request.user.is_superuser
        is_company = True if self.request.user.is_company else False
        if not is_superuser and not is_company:
            messages.error(
                self.request, 'Access Denied!'
            )
            return HttpResponseRedirect(reverse('home'))
        return super(CompanyInvoiceListView, self).dispatch(request, *args, **kwargs)
    
    
    def get_context_data(self, **kwargs):
        context = super(
            CompanyInvoiceListView, self
        ).get_context_data(**kwargs)
        context['page_title'] = 'Invoice List'
        context['page_short_title'] = 'Invoice List'
        context['display_name'] = 'Invoice List'
        context['can_view'] = True
        return context

invoice/templates/invoice/snippets/invoice-pdf-preview.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Titas Invoice</title>
</head>

<style>
    body {
        font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        font-size: 21px;
        line-height: 1.42857143;
        color: #333;
        background-color: #fff;
    }
</style>

<body>

    <div class="container-fluid mt-5 mb-5">

        <div class="row">
            <div class="col-6">
                <div class="mb-2">
                    <h1 class="font-30 font-bold c-text-primary">TITAS</h1>
                </div>
                <h4><b>INVOICE</b> <span class="pull-right">#{{ object.uuid }}</span></h4>
            </div>

            <div class="col-6 text-lg-center">
                <h3 class="m-0">
                    <b class="text-success">{{ object.get_status_str }}</b>
                </h3>
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-6">
                <div class="pull-left">
                    <address>
                        <h4><b>Invoice To</b></h4>
                        <p>
                            <h3>{{ object.get_company }}</h3>
                            Email: {{ object.service.first.company.user.email }} <br>
                            {% if object.service.first.company.address %}
                            Address: {{ object.service.first.company.address }} <br>
                            {% endif %}
                            {% if object.service.first.company.contact %}
                            Contact: {{ object.service.first.company.contact }}
                            {% endif %}
                            {% if object.card_number %}
                            Card Number: {{ object.get_card_number }}
                            {% endif %}
                        </p>
                        <p><b>Invoice Date :</b> {{ object.created_at|date:'Y/m/d' }}</p>
                    </address>
                </div>
            </div>
            <div class="col-6">
                <div class="pull-right text-lg-right">
                    <address>
                        <h4><b>Pay To</b>&nbsp;</h4>
                        <p>
                            <h3>
                                {% if company_information.name %}
                                {{ company_information.name }}
                                {% else %}
                                Example Company
                                {% endif %}
                            </h3>
                            {% if company_information.email %}
                            Email: {{ company_information.email }} <br>
                            {% endif %}
                            {% if company_information.address %}
                            Address: {{ company_information.address }} <br>
                            {% endif %}
                            {% if company_information.contact %}
                            Contact: {{ company_information.contact }}
                            {% endif %}
                        </p>
                    </address>
                </div>
            </div>


            <div class="col-12">
                <div class="table-responsive m-t-40" style="clear: both;">
                    <h4><b>Invoice Items</b></h4>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Description</th>
                                <th class="text-right">Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for service in object.service.all %}
                            <tr>
                                <th>{{ forloop.counter }}</th>
                                <td>
                                    {{ service.name }} ({{ service.registration_date|date:'Y/m/d' }} -
                                    {{ service.due_date|date:'Y/m/d' }})<br>
                                </td>
                                <td class="text-right">
                                    {{ service.price }} {{ service.currency }}
                                </td>
                            </tr>
                            {% endfor %}
                            <tr>
                                <td></td>
                                <td class="text-right" width="80%">
                                    <b>Sub-Total:</b>
                                </td>
                                <td class="text-right">
                                    {{  object.get_service_sub_total }} {{ object.get_currency }}
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="text-right" width="80%">
                                    <b>
                                        Vat{% if object.vat %} ({{ object.vat.vat_percentage }}%){% endif %}:
                                    </b>
                                </td>
                                <td class="text-right">
                                    + {{  object.get_vat_amount }} {{ object.get_currency }}
                                </td>
                            </tr>
                            <tr>
                                <td class="border-none"></td>
                                <td class="text-right border-none" width="80%">
                                    <b>Additional Charge:</b>
                                </td>
                                <td class="text-right border-none">
                                    + {{  object.get_additional_charge }} {{ object.get_currency }}
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="text-right" width="80%">
                                    <b>Total:</b>
                                </td>
                                <td class="text-right">
                                    {{  object.get_subtotal_without_coupon }} {{ object.get_currency }}
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="text-right" width="80%">
                                    <b>Coupon{% if object.coupon %} ({{object.coupon.code}}){% endif %}:</b>
                                </td>
                                <td class="text-right">
                                    - {{  object.coupon.discount_amount }} {{ object.coupon.currency }}
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="text-right" width="80%">
                                    <i><b class="font-17">Grand Total:</b></i>
                                </td>
                                <td class="text-right">
                                    {{  object.total_cost }} {{ object.get_currency }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="mt-2">
            <small>Generated At: {{ datetime|date:"Y-m-d H:i:s" }}</small>
        </div>

    </div>
</body>

</html>

invoice/templates/invoice/snippets/invoice-preview.html
<div class="container">

    <div class="row">
        <div class="col-sm-6">
            <div class="mb-2">
                <h1 class="font-30 font-bold c-text-primary">TITAS</h1>
            </div>
            <h4><b>INVOICE</b> <span class="pull-right">#{{ object.uuid }}</span></h4>
        </div>

        <div class="col-sm-6 text-lg-center">
            <h3 class="m-0">
                <b class="text-success">{{ object.get_status_str }}</b>
            </h3>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-md-6">
            <div class="pull-left">
                <address>
                    <h4><b>Invoice To</b></h4>
                    <p>
                        <h3>{{ object.get_company }}</h3>
                        Email: {{ object.service.first.company.user.email }} <br>
                        {% if object.service.first.company.address %}
                        Address: {{ object.service.first.company.address }} <br>
                        {% endif %}
                        {% if object.service.first.company.contact %}
                        Contact: {{ object.service.first.company.contact }} <br>
                        {% endif %}
                        {% if object.card_number %}
                        Card Number: {{ object.get_card_number }}
                        {% endif %}
                    </p>
                    <p><b>Invoice Date :</b> {{ object.created_at|date:'Y/m/d' }}</p>
                </address>
            </div>
        </div>
        <div class="col-md-6">
            <div class="pull-right text-lg-right">
                <address>
                    <h4><b>Pay To</b>&nbsp;</h4>
                    <p>
                        <h3>
                            {% if company_information.name %}
                            {{ company_information.name }}
                            {% else %}
                            Example Company
                            {% endif %}
                        </h3>
                        {% if company_information.email %}
                        Email: {{ company_information.email }} <br>
                        {% endif %}
                        {% if company_information.address %}
                        Address: {{ company_information.address }} <br>
                        {% endif %}
                        {% if company_information.contact %}
                        Contact: {{ company_information.contact }}
                        {% endif %}
                    </p>
                </address>
            </div>
        </div>


        <div class="col-md-12">
            <div class="table-responsive m-t-40" style="clear: both;">
                <h4><b>Invoice Items</b></h4>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Description</th>
                            <th class="text-right">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for service in object.service.all %}
                        <tr>
                            <th>{{ forloop.counter }}</th>
                            <td>
                                {{ service.name }} ({{ service.registration_date|date:'Y/m/d' }} -
                                {{ service.due_date|date:'Y/m/d' }})<br>
                            </td>
                            <td class="text-right">
                                {{ service.price }} {{ service.currency }}
                            </td>
                        </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td class="text-right" width="80%">
                                <b>Sub-Total:</b>
                            </td>
                            <td class="text-right">
                                {{  object.get_service_sub_total }} {{ object.get_currency }}
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td class="text-right" width="80%">
                                <b>
                                    Vat{% if object.vat %} ({{ object.vat.vat_percentage }}%){% endif %}:
                                </b>
                            </td>
                            <td class="text-right">
                                + {{  object.get_vat_amount }} {{ object.get_currency }}
                            </td>
                        </tr>
                        <tr>
                            <td class="border-none"></td>
                            <td class="text-right border-none" width="80%">
                                <b>Additional Charge:</b>
                            </td>
                            <td class="text-right border-none">
                                + {{  object.get_additional_charge }} {{ object.get_currency }}
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td class="text-right" width="80%">
                                <b>Total:</b>
                            </td>
                            <td class="text-right">
                                {{  object.get_subtotal_without_coupon }} {{ object.get_currency }}
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td class="text-right" width="80%">
                                <b>Coupon{% if object.coupon %} ({{object.coupon.code}}){% endif %}:</b>
                            </td>
                            <td class="text-right">
                                - {{  object.coupon.discount_amount }} {{ object.coupon.currency }}
                            </td>
                        </tr>
                        <tr>
                            <td></td>
                            <td class="text-right" width="80%">
                                <i><b class="font-17">Grand Total:</b></i>
                            </td>
                            <td class="text-right">
                                {{  object.total_cost }} {{ object.get_currency }}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-md-12 mt-4">
            <a href="{% url 'invoice:invoice_pdf_download' slug=object.slug %}">
                <span><i class="fa fa-arrow-circle-down"></i> Download PDF</span>
            </a>
        </div>
    </div>

</div>