cards/urls.py
from django.urls import path
from .views import CardCreateView, CardUpdateView, CardDetailView, delete_card, CardListView

urlpatterns = [
    # ==============================*** Card URLS ***==============================
    path("create/", CardCreateView.as_view(), name="create_card"),
    # path("update/<slug>/", CardUpdateView.as_view(), name="update_card"),
    path("<slug>/detail/", CardDetailView.as_view(), name="card_detail"),
    # path("delete/", delete_card, name="delete_card"),
    # Card List View for admin usage
    path("list/", CardListView.as_view(), name="admin_card_list"),
]

company/urls.py
from django.urls import path
from .views import CompanyCreateView, ComapnyUpdateView, CompanyDetailView, delete_company

urlpatterns = [
    # ==============================*** Company URLS ***==============================
    path("create/", CompanyCreateView.as_view(), name="create_company"),
    path("update/<slug>/", ComapnyUpdateView.as_view(), name="update_company"),
    path("<slug>/detail/", CompanyDetailView.as_view(), name="company_detail"),
    path("delete/", delete_company, name="delete_company"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve
import debug_toolbar
# views
from .user_panel_views import HomepageView
from .dashboard_views import DashboardView
from django.conf.urls import handler404, handler500


THIRD_PARTY_URL_PATTERNS = [
    # Django Allauth URLs
    path('accounts/', include('allauth.urls')),
    # Django Select2
    path("select2/", include("django_select2.urls")),
]

END_USER_URL_PATTERNS = [
    # User panel URLs
    path('', DashboardView.as_view(), name='home'),
]

ADMIN_URL_PATTERNS = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # ==============================*** User URLS ***==============================
    path("users/", include(("users.urls", "users"), namespace="users")),
    # ==============================*** Company URLS ***==============================
    path("company/", include(("company.urls", "company"), namespace="company")),
    # ==============================*** Service URLS ***==============================
    path("service/", include(("service.urls", "service"), namespace="service")),
    # ==============================*** Deals URLS ***==============================
    path("deals/", include(("deals.urls", "deals"), namespace="deals")),
    # ==============================*** Invoice URLS ***==============================
    path("invoice/", include(("invoice.urls", "invoice"), namespace="invoice")),
    # ==============================*** Cards URLS ***==============================
    path("server-service-payment/", include(("cards.urls", "cards"), namespace="cards")),
]

urlpatterns = [
    # For handling Static Files in Debug False Mode
    # url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    # ==============================*** UTILS URLS ***==============================
    path("utils/", include(("utils.urls", "utils"), namespace="utils")),
] + THIRD_PARTY_URL_PATTERNS + END_USER_URL_PATTERNS + ADMIN_URL_PATTERNS


# Exception Handlers
handler500 = 'config.user_panel_views.server_error'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        # Django Debug Toolbar
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

invoice/urls.py
from django.urls import path
from .views import InvoiceCreateView, InvoiceUpdateView, InvoiceDetailView, delete_invoice, GeneratePdf, CompanyInvoiceListView

urlpatterns = [
    # ==============================*** Invoice URLS ***==============================
    path("create/", InvoiceCreateView.as_view(), name="create_invoice"),
    path("update/<slug>/", InvoiceUpdateView.as_view(), name="update_invoice"),
    path("<slug>/detail/", InvoiceDetailView.as_view(), name="invoice_detail"),
    path("delete/", delete_invoice, name="delete_invoice"),
    # PDF URLs
    path("<slug>/pdf/", GeneratePdf.as_view(), name="invoice_pdf_download"),
    # Company Invoice List
    path("list/", CompanyInvoiceListView.as_view(), name="company_invoice_list"),
]

service/urls.py
from django.urls import path
from .views import ServiceCreateView, ServiceUpdateView, ServiceDetailView, delete_service

urlpatterns = [
    # ==============================*** Service URLS ***==============================
    path("create/", ServiceCreateView.as_view(), name="create_service"),
    path("update/<slug>/", ServiceUpdateView.as_view(), name="update_service"),
    path("<slug>/detail/", ServiceDetailView.as_view(), name="service_detail"),
    path("delete/", delete_service, name="delete_service"),
]

utils/urls.py
from django.urls import path
from .views import (
    DashboardSettingView,
    ConfigurationCreateView, ConfigurationUpdateView, ConfigurationDetailView, delete_configuration
)


urlpatterns = [
    path('dashboard-setting/', DashboardSettingView.as_view(), name="dashboard_setting"),
    # ==============================*** Configuration URLS ***==============================
    path("configuration/create/", ConfigurationCreateView.as_view(), name="create_configuration"),
    path("configuration/update/<slug>/", ConfigurationUpdateView.as_view(), name="update_configuration"),
    path("configuration/<slug>/detail/", ConfigurationDetailView.as_view(), name="configuration_detail"),
    path("configuration/delete/", delete_configuration, name="delete_configuration"),
]

utils/forms.py
from django import forms
from utils.mixins import CustomSimpleForm, CustomModelForm
from .models import Configuration
from django_select2.forms import ModelSelect2Widget


class DateInput(forms.DateInput):
    input_type = 'date'


class ConfigurationManageForm(CustomModelForm):

    class Meta:
        model = Configuration
        fields = ['payment_amount', 'currency', 'card_page_title', 'is_active']

utils/views.py
from .models import DashboardSetting, Configuration
from django.http import JsonResponse
from django.views.generic import View
import json
from django.utils import timezone
from .decorators import has_dashboard_permission_required
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from utils.helpers import (
    validate_normal_form, get_simple_context_data, get_simple_object, delete_simple_object, user_has_permission
)
from django.views.generic import CreateView, UpdateView, DetailView
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.contrib import messages
from .forms import ConfigurationManageForm


dashboard_decorators = [login_required, has_dashboard_permission_required]


""" 
-------------------------------------------------------------------
                        ** Dashboard Setting ***
-------------------------------------------------------------------
"""


@method_decorator(dashboard_decorators, name='dispatch')
class DashboardSettingView(View):

    def post(self, *args, **kwargs):

        if self.request.is_ajax and self.request.method == "POST":
            try:
                # Get Config Values
                dashboard_setting = json.loads(
                    self.request.body).get("setting-object", None)
                """
                Example Request Body Object:
                "setting-object": {
                    key: "skin-config",
                    value: value
                }
                """
                # define available keys
                available_keys = ["skin-config", "menu-collapsed-config", "layout-width-config",
                                  "navbar-color-config", "navbar-type-config", "footer-type-config"]

                # get setting key
                setting_key = dashboard_setting.get("key", [])

                if setting_key in available_keys:
                    # get setting value
                    setting_value = dashboard_setting.get("value", None)

                    # get all objects of DashboardSetting
                    dashboard_setting_qs = DashboardSetting.objects.all()

                    # check if dashboard setting object exists, if not then create a DashboardSetting object
                    if dashboard_setting_qs:
                        pass
                    else:
                        DashboardSetting.objects.create(
                            title="Dashboard"
                        )

                    # update dashboard setting based on setting key
                    if setting_key == "skin-config":
                        dashboard_setting_qs.update(
                            skin=setting_value, updated_at=timezone.now()
                        )
                    elif setting_key == "menu-collapsed-config":
                        dashboard_setting_qs.update(
                            menu_collapsed=setting_value, updated_at=timezone.now()
                        )
                    elif setting_key == "layout-width-config":
                        dashboard_setting_qs.update(
                            layout_width=setting_value, updated_at=timezone.now()
                        )
                    elif setting_key == "navbar-color-config":
                        dashboard_setting_qs.update(
                            navbar_color=setting_value, updated_at=timezone.now()
                        )
                    elif setting_key == "navbar-type-config":
                        dashboard_setting_qs.update(
                            navbar_type=setting_value, updated_at=timezone.now()
                        )
                    elif setting_key == "footer-type-config":
                        dashboard_setting_qs.update(
                            footer_type=setting_value, updated_at=timezone.now()
                        )
                    else:
                        dashboard_setting_qs.update(
                            title="Dashboard", updated_at=timezone.now()
                        )
                else:
                    raise ValueError(
                        f"Invalid key: {setting_key} given! Available keys are {available_keys}"
                    )
                return JsonResponse({"valid": True}, status=200)
            except Exception as E:
                return JsonResponse({"valid": False, "Exception": str(E)}, status=400)
        return JsonResponse({}, status=400)


""" 
-------------------------------------------------------------------
                        ** Configuration ***
-------------------------------------------------------------------
"""


def get_configuration_common_contexts(request):
    # Hide Create Option if vat already exists
    extra_kwargs = {}
    if len(Configuration.objects.all()) >= 1:
        extra_kwargs["create_url"] = None

    common_contexts = get_simple_context_data(
        request=request, app_namespace='utils', model_namespace="configuration", model=Configuration, list_template=None, fields_to_hide_in_table=["id"], **extra_kwargs
    )
    return common_contexts


@method_decorator(dashboard_decorators, name='dispatch')
class ConfigurationCreateView(CreateView):
    template_name = "admin_panel/snippets/manage.html"
    form_class = ConfigurationManageForm

    def form_valid(self, form, **kwargs):
        messages.success(
            self.request, 'Configuration created successfully!'
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("utils:create_configuration")

    def get_context_data(self, **kwargs):
        context = super(
            ConfigurationCreateView, self
        ).get_context_data(**kwargs)
        context['page_title'] = 'Create Configuration'
        context['page_short_title'] = 'Create Configuration'
        for key, value in get_configuration_common_contexts(request=self.request).items():
            context[key] = value
        return context


@method_decorator(dashboard_decorators, name='dispatch')
class ConfigurationDetailView(DetailView):
    template_name = "admin_panel/snippets/detail-common.html"

    def get_object(self):
        return get_simple_object(key='slug', model=Configuration, self=self)

    def get_context_data(self, **kwargs):
        context = super(
            ConfigurationDetailView, self
        ).get_context_data(**kwargs)
        context['page_title'] = 'Configuration Detail'
        context['page_short_title'] = 'Configuration Detail'
        for key, value in get_configuration_common_contexts(request=self.request).items():
            context[key] = value
        return context


@method_decorator(dashboard_decorators, name='dispatch')
class ConfigurationUpdateView(UpdateView):
    template_name = 'admin_panel/snippets/manage.html'
    form_class = ConfigurationManageForm

    def get_object(self):
        return get_simple_object(key="slug", model=Configuration, self=self)

    def get_success_url(self):
        return reverse("utils:create_configuration")

    def form_valid(self, form):
        messages.success(
            self.request, 'Configuration updated successfully!'
        )
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(
            ConfigurationUpdateView, self
        ).get_context_data(**kwargs)
        context['page_title'] = 'Update Configuration'
        context['page_short_title'] = 'Update Configuration'
        for key, value in get_configuration_common_contexts(request=self.request).items():
            context[key] = value
        return context


@csrf_exempt
@has_dashboard_permission_required
@login_required
def delete_configuration(request):
    return delete_simple_object(request=request, key='slug', model=Configuration, redirect_url="utils:create_configuration")

templates/admin_panel/components/breadcrumb.html
{% load custom_tags %}
{% url 'dashboard' as dashboard_url %}

<div class="content-header row">
    <div class="content-header-left col-md-9 col-12 mb-2">
        <div class="row breadcrumbs-top">
            <div class="col-12">
                <h4 class="content-header-title float-left mb-0">{{ page_title|truncate_word:50 }}</h4>
                <div class="breadcrumb-wrapper">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
                        {% if not request.path == dashboard_url %}
                        <li class="breadcrumb-item active">{{ page_title|truncate_word:50 }}</li>
                        {% endif %}
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>

templates/admin_panel/components/footer.html
<div class="sidenav-overlay"></div>
<div class="drag-target"></div>
<footer class="{{ dashboard_setting.get_footer_type }}">
    <p class="clearfix mb-0">
        <span class="float-md-left d-block d-md-inline-block mt-25">COPYRIGHT &copy; {% now "F Y" %}
            <a class="ml-25" href="#">Titas</a>
            <span class="d-none d-sm-inline-block">, All rights Reserved</span>
        </span>
        {% comment %}
        <span class="float-md-right d-none d-md-block">
            <i data-feather="heart"></i>
        </span>
        {% endcomment %}
    </p>
</footer>
<button class="btn btn-primary btn-icon scroll-top" type="button"><i data-feather="arrow-up"></i></button>

templates/admin_panel/components/header.html
{% load static %}

{% url 'account_signup' as signup_url %}
{% url 'account_login' as login_url %}
{% url 'account_logout' as logout_url %}

<nav
    class="header-navbar navbar navbar-expand-lg align-items-center {{ dashboard_setting.get_navbar_type }} {{ dashboard_setting.navbar_color }} navbar-shadow">
    <div class="navbar-container d-flex content">
        <div class="bookmark-wrapper d-flex align-items-center">
            <ul class="nav navbar-nav d-xl-none">
                <li class="nav-item">
                    <a class="nav-link menu-toggle" href="javascript:void(0);">
                        <i class="ficon" data-feather="menu"></i>
                    </a>
                </li>
            </ul>
        </div>

        {% if not request.user.is_authenticated %}
        <ul class="nav navbar-nav align-items-center ml-auto">
            <li class="nav-item d-none d-lg-block">
                <a href="{{ signup_url }}" class="btn btn-primary btn-md fw-bold">
                    <i class="fa fa-plus-circle"></i> Signup
                </a>
            </li>
            <li class="nav-item d-none d-lg-block ml-2">
                <a href="{{ login_url }}" class="btn btn-success btn-md fw-bold">
                    <i class="fa fa-location-arrow"></i> Login
                </a>
            </li>
        </ul>
        {% else %}
        <ul class="nav navbar-nav align-items-center ml-auto">
            <li class="nav-item dropdown dropdown-user">
                <a class="nav-link dropdown-toggle dropdown-user-link" id="dropdown-user" href="javascript:void(0);"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="user-nav d-sm-flex d-none">
                        <span class="user-name font-weight-bolder">
                            {{ request.user.get_dynamic_username }}
                        </span>
                        <span class="user-status">
                            {% if request.user.is_staff == True %}
                            Admin
                            {% elif request.user.is_company == True %}
                            Company User
                            {% else %}
                            Regular User
                            {% endif %}
                        </span>
                    </div>
                    <span class="avatar">
                        {% comment %}
                        <img class="round" src="{% static 'admin_panel/assets/images/avatar-s-11.jpg' %}" alt="avatar" height="40"
                            width="40">
                        {% endcomment %}
                        <i class="fas fa-user font-20 round p-1"></i>
                        <span class="avatar-status-online"></span>
                    </span>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-user">
                    <a class="dropdown-item" href="{% url 'account_email' %}">Manage Account</a>
                    <a class="dropdown-item" href="{% url 'account_change_password' %}">Change Password</a>
                    <a class="dropdown-item" data-toggle="modal" data-target="#logoutModal">
                        <i class="mr-50" data-feather="power"></i>
                        Logout
                    </a>
                </div>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>

{% include "admin_panel/components/logout-modal.html" %}

templates/admin_panel/components/left-sidebar.html
<div class="main-menu menu-fixed {{ dashboard_setting.get_menu_class }} menu-accordion menu-shadow" data-scroll-to-active="true">
    <div class="navbar-header">
        <ul class="nav navbar-nav flex-row">
            <li class="nav-item mr-auto"><a class="navbar-brand" href="{% url 'dashboard' %}">
                    <!-- <span class="brand-logo">
                    </span> -->
                    <h2 class="brand-text">{{ dashboard_setting.title }}</h2>
                </a></li>
            <li class="nav-item nav-toggle"><a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse"><i
                        class="d-block d-xl-none text-primary toggle-icon font-medium-4" data-feather="x"></i><i
                        class="d-none d-xl-block collapse-toggle-icon font-medium-4  text-primary" data-feather="disc"
                        data-ticon="disc"></i></a></li>
        </ul>
    </div>
    
    <div class="shadow-bottom"></div>

    <!-- BEGIN: Main-Menu-Content -->
    <nav class="main-menu-content mt-2">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
            <li class="nav-item">
                <a class="d-flex align-items-center" href="{% url 'dashboard' %}">
                    <i class="fas fa-tachometer-alt"></i>
                    <span class="menu-title text-truncate" data-i18n="Dashboard">Dashboard</span>
                </a>
            </li>

            {% if request.user.is_superuser %}

            <li class="nav-item">
                <a class="d-flex align-items-center" href="{% url 'users:create_user' %}">
                    <i class="fas fa-user"></i>
                    <span class="menu-title text-truncate" data-i18n="User">User</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="d-flex align-items-center" href="{% url 'company:create_company' %}">
                    <i class="fas fa-building"></i>
                    <span class="menu-title text-truncate" data-i18n="Company">Company</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="d-flex align-items-center" href="{% url 'service:create_service' %}">
                    <i class="fas fa-briefcase"></i>
                    <span class="menu-title text-truncate" data-i18n="Service">Service</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="d-flex align-items-center" href="{% url 'deals:create_coupon' %}">
                    <i class="fas fa-font"></i>
                    <span class="menu-title text-truncate" data-i18n="Coupon">Coupon</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="d-flex align-items-center" href="{% url 'deals:create_vat' %}">
                    <i class="fas fa-percentage"></i>
                    <span class="menu-title text-truncate" data-i18n="Vat">Vat</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="d-flex align-items-center" href="{% url 'invoice:create_invoice' %}">
                    <i class="fas fa-file-invoice"></i>
                    <span class="menu-title text-truncate" data-i18n="Invoice">Invoice</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="d-flex align-items-center" href="{% url 'utils:create_configuration' %}">
                    <i class="fas fa-cogs"></i>
                    <span class="menu-title text-truncate" data-i18n="Invoice">Configuration</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="d-flex align-items-center" href="{% url 'cards:admin_card_list' %}">
                    <i class="fas fa-credit-card"></i>
                    <span class="menu-title text-truncate" data-i18n="Invoice">Service Payment List</span>
                </a>
            </li>

            {% endif %}

            {% if request.user.is_company %}

            <li class="nav-item">
                <a class="d-flex align-items-center" href="{% url 'invoice:company_invoice_list' %}">
                    <i class="fas fa-file-invoice"></i>
                    <span class="menu-title text-truncate" data-i18n="Invoice">Invoices</span>
                </a>
            </li>

            {% endif %}

            {% if request.user.is_authenticated and not request.user.is_superuser %}

            <li class="nav-item">
                <a class="d-flex align-items-center" href="{% url 'cards:create_card' %}">
                    <i class="fas fa-credit-card"></i>
                    <span class="menu-title text-truncate" data-i18n="Service Payment">Service Payment</span>
                </a>
            </li>

            {% endif %}

        </ul>
    </nav>
    <!-- END: Main-Menu-Content -->

</div>

templates/admin_panel/components/logout-modal.html
{% url 'account_logout' as logout_url %}
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
                <form method="POST" action="{{ logout_url }}">
                    {% csrf_token %}
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger">Yes, Logout</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/admin_panel/components/meta-tags.html
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0,minimal-ui">
<meta name="description" content="Admin Panel Dashboard. Contributor: Numan Ibn Mazid. Created by: Rapples Limited.">
<meta name="keywords" content="Numan Ibn Mazid, Rapples Limited, Admin panel, Dashboard">
<meta name="author" content="Numan Ibn Mazid">

templates/admin_panel/components/scripts.html
{% load static %}

<!-- BEGIN: Page Vendor JS-->
<!-- END: Page Vendor JS-->

<!-- BEGIN: Ajax Setup-->
<script src="{% static 'admin_panel/assets/js/ajax-setup.js' %}"></script>
<!-- END: Ajax Setup-->

<!-- BEGIN: Theme JS-->
<script src="{% static 'admin_panel/assets/js/app-menu.js' %}"></script>
<script src="{% static 'admin_panel/assets/js/app.js' %}"></script>
<script src="{% static 'admin_panel/assets/js/customizer.min.js' %}"></script>
<script src="{% static 'admin_panel/assets/js/theme-customizer.js' %}"></script>
<!-- END: Theme JS-->

<!-- Sweet Alert -->
<script src="{% static 'admin_panel/vendors/sweetalert/sweetalert.min.js' %}"></script>

<!-- BEGIN: Bootstrap Validator JS-->
<script src="{% static 'vendors/bootstrap-validator/validator.min.js' %}"></script>
<!-- END: Bootstrap Validator JS-->

<!-- BEGIN: Custom JS-->
<script src="{% static 'admin_panel/assets/js/scripts.js' %}"></script>
<script src="{% static 'admin_panel/assets/js/custom.js' %}"></script>
<script src="{% static 'scripts/custom.js' %}"></script>
<!-- END: Custom JS-->

<script>
    $(window).on('load', function () {
        if (feather) {
            feather.replace({
                width: 14,
                height: 14
            });
        }
    })
</script>

templates/admin_panel/components/styles.html
{% load static %}

<link rel="apple-touch-icon" href="{% static 'admin_panel/assets/images/ico/favicon.ico' %}">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'admin_panel/assets/images/ico/favicon.ico' %}">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600"
    rel="stylesheet">

<!-- BEGIN: Vendor CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'admin_panel/assets/css/vendors.min.css' %}">
<!-- END: Vendor CSS-->

<!-- BEGIN: Theme CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'admin_panel/assets/css/bootstrap.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin_panel/assets/css/bootstrap-extended.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin_panel/assets/css/colors.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin_panel/assets/css/components.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin_panel/assets/css/dark-layout.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin_panel/assets/css/bordered-layout.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin_panel/assets/css/semi-dark-layout.css' %}">

<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'admin_panel/assets/css/vertical-menu.css' %}">
<!-- END: Page CSS-->

<!-- BEGIN: Font-Awesome CSS-->
<link rel="stylesheet" href="{% static 'admin_panel/vendors/fontawesome/all.min.css' %}">
<!-- END: Font-Awesome CSS-->

<!-- BEGIN: Custom CSS-->
<link rel="stylesheet" type="text/css" href="{% static 'admin_panel/assets/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'admin_panel/assets/css/custom.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/custom.css' %}" />
<!-- END: Custom CSS-->

<!-- BEGIN: Vendor JS-->
<script src="{% static 'admin_panel/assets/js/vendors.min.js' %}"></script>
<!-- BEGIN Vendor JS-->

templates/admin_panel/components/utils.html
{% load static %}

<input type="hidden" name="static-assets-url" id="static-assets-url" value="{% static 'admin_panel/assets' %}/">